import { TylerIconRegistry } from '@tylertech/tyler-components-web';
import {
  tylIconArrowBack,
  tylIconDashboard,
  tylIconPerson,
  tylIconListAlt,
  tylIconPets,
  tylIconChildFriendly,
  tylIconHome,
  tylIconMenu,
  tylIconSearch,
  tylIconCategory,
  tylIconFilterList,
  tylIconDelete,
  tylIconAdd,
  tylIconAddCircle,
  tylIconArrowDropDown,
  tylIconEdit,
  tylIconContentCopy,
  tylIconBolt,
  tylIconCheck,
  tylIconViewColumn,
  tylIconChevronLeft,
  tylIconChevronRight,
  tylIconClose,
  tylIconMap,
  tylIcon360,
  tylIconExpandLess,
  tylIconExpandMore,
  tylIconKeyboardArrowRight,
  tylIconDirections
} from '@tylertech/tyler-icons/standard';

const standardIcons = [
  tylIconArrowBack,
  tylIconDashboard,
  tylIconPerson,
  tylIconListAlt,
  tylIconPets,
  tylIconChildFriendly,
  tylIconHome,
  tylIconMenu,
  tylIconSearch,
  tylIconCategory,
  tylIconFilterList,
  tylIconDelete,
  tylIconAdd,
  tylIconAddCircle,
  tylIconArrowDropDown,
  tylIconEdit,
  tylIconContentCopy,
  tylIconBolt,
  tylIconCheck,
  tylIconViewColumn,
  tylIconChevronLeft,
  tylIconChevronRight,
  tylIconClose,
  tylIconMap,
  tylIcon360,
  tylIconExpandLess,
  tylIconExpandMore,
  tylIconKeyboardArrowRight,
  tylIconDirections
];

export const defineIcons = () => {
  TylerIconRegistry.define(standardIcons);
};
